name: ClansLegendaries
main: me.libraryaddictfan.ClansLegendaries
version: 1.4
authors: [None Really]
commands:
   legendary:
      description: Gives a Legendary
      usage: /<command>
      aliases: [leg]
   legendaries:
      description: Sets options for the plugin
      usage: /<command>